general.import = [
  "/usr/local/lib/node_modules/alacritty-themes/themes/Catppuccin-Mocha.toml"
]

[env]
TERM = "xterm-256color"

[window]
decorations = "Full"

opacity = 0.95
blur = true

[font]
size = 18
normal = { family = "0xProto Nerd Font" }
